### ISSUE TITLE
Do we have to compute parametric t in AABB::ray_intersect?

### ISSUE THREAD

**Issue by ozkazanc** [dilevin/computer-graphics-bounding-volume-hierarchy#14]
I don't understand how we can compute t in AABB::ray_intersect since ray_intersect_box function does not return a t if a ray intersects with a given box. But we need to compute t to determine the closest object that was hit, right? Or is there something I'm missing?

**Comment by rin-23** [comment]
ray_intersect_box is there to prevent you from recursively calling ray_intersect on the children nodes.

if the ray hit the box then you need to recursively call ray_intersect on left and right children.  Eventually you will get to the leafs (like a mesh triangle) which will give you the value t.

**Comment by rin-23** [comment]
Check Object.h and the virtual function ray_intersect. Multiple other classes are children of Object class and override ray_intersect function.

**Comment by ozkazanc** [comment]
Alright, thank you!

**Comment by MstrPikachu** [comment]
Is there a reason why we use DFS for this instead of a BFS like point-AABB tree distance query? These are very similar and ray-AABBTree intersect is like finding the closest parametric t, similar to like point query for closest distance. I don't see why DFS would be preferred except for code simplicity.
