### ISSUE TITLE
Why RowVector3d?

### ISSUE THREAD

**Issue by wangshangsam** [dilevin/computer-graphics-bounding-volume-hierarchy#4]
Is there a particular reason why we are using RowVector3d in this assignment instead of Vector3d which was consistent throughout the previous assignments?

**Comment by dilevin** [comment]
This assignment deals with triangle mesh (we'll discuss those next lecture) not triangle soups. We store meshes as two matrices. The first is an n by 3 matrix which stores n 3D vertices as the rows of the matrix. In order to work with individual vertices you will extract rows from this matrix. Hence the use of RowVector rather than Vector.
