### ISSUE TITLE
point_triangle_squared_distance function not used

### ISSUE THREAD

**Issue by IgorStempen** [dilevin/computer-graphics-bounding-volume-hierarchy#7]
Hi,

The point_triangle_squared_distance function is not needed to complete this lab.

A question was asked last year regarding this same problem, and the response was that we still need to implement this function and test it ourselves:

[https://github.com/alecjacobson/computer-graphics-bounding-volume-hierarchy/issues/14#issue-367408963](url)

_**if the link above doesn't work, just copy and paste it into the url search of your browser_

Is this still expected this semester?

**Comment by rin-23** [comment]
We decided to make this function count as a bonus. So you don't have to implement it to get full marks.
But if you do you will receive extra marks.

**Comment by wangshangsam** [comment]
What are you guys talking about?

Based on MeshTriangle.h:
=================================
// Simple wrapper around `point_triangle_squared_distance`
inline bool MeshTriangle::point_squared_distance(
  const Eigen::RowVector3d & query,
  const double min_sqrd,
  const double max_sqrd,
  double & sqrd,
  std::shared_ptr<Object> & descendant) const
{
  Eigen::RowVector3d bary;
  sqrd = point_triangle_squared_distance(
    query,
    V.row(F(f,0)),
    V.row(F(f,1)),
    V.row(F(f,2)),
    bary);
  // descendant doesn't make sense so it's not touched
  return (sqrd >= min_sqrd && sqrd < max_sqrd);
}
====================================

So it seems point_triangle_squared_distance() is needed. The real question is how, since it is not covered anywhere in the lecture.

**Comment by IgorStempen** [comment]
But MeshTriangle::point_squared_distance is not needed to complete the lab.

**Comment by leoouyang** [comment]
Can we get a confirmation on this?

**Comment by rin-23** [comment]
you dont need to implement it
